### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by SureshKumar344** [icapps/flutter-background-location-tracker#34]
Getting this exception while passing the trackingInterval as integer

Can you pls update this lib based on the solution provided in the below link

https://github.com/dotintent/FlutterBleLib/commit/4069052715e5e9e17c831f597f55fdeb62548f4c

**Comment by vanlooverenkoen** [comment]
Thanks for reporting, I am reviewing this plugin today to fix open issues where possible.

**Comment by vanlooverenkoen** [comment]
Fixed here: dd1ad315d5d208f217f9e53e0de47ae4d74d5ad5

**Comment by vanlooverenkoen** [comment]
Should be fixed in #40
