### ISSUE TITLE
in IOS not working when app is killed

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [icapps/flutter-background-location-tracker#38]
It's working when the app is in the foreground, but when I close the app, not updating. 

by the way, I got the always permission. there is no problem with permissions

**Comment by Shahmirzali-Huseynov** [comment]
[background_example.zip](https://github.com/icapps/flutter-background-location-tracker/files/8804270/background_example.zip)


Yes, this is the example project. first I get LocationWhenInUse permission after Always, and then in the foreground is working. but when the app is killed not work. 

thank you for replying and helping.

**Comment by Shahmirzali-Huseynov** [comment]
I tried real device (iphone 8 ios 15.5) and used your example project codes. unfortunately I don't have logs. but say me If you need something and how , I can provide you.

**Comment by vanlooverenkoen** [comment]
@Shahmirzali-Huseynov I have updated the example project. maybe you did not change the distance filter. (I forgot to change that as well, but after setting that to null I got updates every x seconds. while connected to my PC)

**Comment by Shahmirzali-Huseynov** [comment]
@vanlooverenkoen you mean If I define distanceFilterMeters to null it will work?

**Comment by vanlooverenkoen** [comment]
I am not sure how you are testing. But the distanceFilterMeters are set to 5. so If you don't move more than 5m you will not get any updates.

**Comment by Shahmirzali-Huseynov** [comment]
I tried your #40 example project. this function didn't affect. is it working for you?

`  final result = await Permission.locationAlways.request();`

**Comment by vanlooverenkoen** [comment]
What do you mean by `killed`? Completely removed from the resent apps? Or just send to the background. Because if you force quit the app from recents apple will kill all services and background services linked to your app

**Comment by vanlooverenkoen** [comment]
Let me double check that today.

**Comment by vanlooverenkoen** [comment]
I forgot to add: 
```
        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',
```

The pr is updated

**Comment by Shahmirzali-Huseynov** [comment]
@vanlooverenkoen  Did you test example #40 in release run on real device IOS ? because when I run the app in debug mode location tracking(not background, when is killed), but when I release run, location tracking not working even app isn't killed or on background/foreground. request permission working but tracking not working completely(run release).

**Comment by vanlooverenkoen** [comment]
Hmm you could also run on simulator and select bikeride for example. 
But in my case everything is working fine.
Did you set your permissions to always allow

**Comment by Shahmirzali-Huseynov** [comment]
@vanlooverenkoen I mean in Release mode completely not working location tracking, even app is alive.

**Comment by Shahmirzali-Huseynov** [comment]
Can you test release mode on Real device IOS? when it's possible

**Comment by vanlooverenkoen** [comment]
That is normal. 

> What do you mean by killed? Completely removed from the resent apps? Or just send to the background. Because if you force quit the app from recents apple will kill all services and background services linked to your app

Can you test by just closing the app **but not killing the app**. That should work normally.

**Comment by vanlooverenkoen** [comment]
I will also test on a real device. Thanks already for your feedback!! Much appreciated!

**Comment by vanlooverenkoen** [comment]
Alright yes. killed state that is to be expected. That is an OS limitation.

I will check the release mode later today or tomorrow.

**Comment by vanlooverenkoen** [comment]
Indeed I am not receiving anything in release. That is strange. Let me investigate.

**Comment by Shahmirzali-Huseynov** [comment]
Yes, location permission is working, but Tracking is not. I think Blue pill means the app has always location permission and be attention the app can track or track your location.

**Comment by vanlooverenkoen** [comment]
No blue pill actually means that is tracking in the background. Which it is doing. We are just doing the correct thing in the dart implementation.

If you open your console. on mac you can see the extra logs to debug the native part.
<img width="638" alt="image" src="https://user-images.githubusercontent.com/21172855/189120630-d09f6a13-5f7c-48ab-84e0-f29540d54a9e.png">

**Comment by Shahmirzali-Huseynov** [comment]
Okay, thank you for your effort. I will wait :)

**Comment by vanlooverenkoen** [comment]
```
Runner	14:46:07.056512+0200	[VERBOSE-2:dart_isolate.cc(668)] Could not resolve main entrypoint function.
Runner	14:46:07.056672+0200	[VERBOSE-2:dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
Runner	14:46:07.057252+0200	[VERBOSE-2:runtime_controller.cc(385)] Could not create root isolate.
Runner	14:46:07.057945+0200	[VERBOSE-2:shell.cc(604)] Could not launch engine with configuration.
```

This is probably the same issue as we had on android. It will probably be a `long` instead of an `int`

**Comment by vanlooverenkoen** [comment]
Very weird that it does work ik debug on a real device. But not in release on a real device. 🤯

**Comment by vanlooverenkoen** [comment]
I am getting the same error in release on Android. 🤯 
It seems to be a flutter issue. because it is working perfectly in debug

**Comment by vanlooverenkoen** [comment]
I think I found it!! There was a bug related to this. (https://github.com/flutter/flutter/issues/91841#issuecomment-1006026551)

I found that I had to add the `@pramga('vm:entry-point')` to make it work in release

```
@pragma('vm:entry-point')
void backgroundCallback() {
  BackgroundLocationTrackerManager.handleBackgroundUpdated(
    (data) async => Repo().update(data),
  );
}
```

**Comment by vanlooverenkoen** [comment]
@Shahmirzali-Huseynov is it possible to test again?

**Comment by vanlooverenkoen** [comment]
I will be fixing the comments on my pull request. and after that, I will close it.
