### ISSUE TITLE
FATAL EXCEPTION: main 

### ISSUE THREAD

**Issue by rmanoop25** [icapps/flutter-background-location-tracker#43]
This is Happening when I use this plugin along with the latest version of geolocator plugin.

Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~bs8tIWx2JYw5t4e3ku639w==/com.fieldmanager_hrms.flutter.fieldmanager_hrms_flutter-5CxcyFvvzlFb-K_H0W66IQ==/base.apk)
E/AndroidRuntime(10302): 	at com.icapps.background_location_tracker.service.LocationUpdatesService.getLastLocation(LocationUpdatesService.kt:215)
E/AndroidRuntime(10302): 	at com.icapps.background_location_tracker.service.LocationUpdatesService.onCreate(LocationUpdatesService.kt:74)
E/AndroidRuntime(10302): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5060)
E/AndroidRuntime(10302): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(10302): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
E/AndroidRuntime(10302): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10302): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(10302): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(10302): 	at android.app.ActivityThread.main(ActivityThread.java:8741)
E/AndroidRuntime(10302): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10302): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(10302): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by gauravmehta13** [comment]
Facing same in flutter 3.7

**Comment by rmanoop25** [comment]
I got it fixed. I this this issue is due to google location service conflict. In the latest geolocator plugin it is using 21.x version. I downgraded the geolocator plugin to 8.x version that resulted it to use older version of google play location service that fixed the issue. Now all working well.

**Comment by gauravmehta13** [comment]
@rmanoop25  Please reopen this since downgrading the package is not a long term solution, 
It would be great if 
flutter-background-location-tracker can support this change

**Comment by gauravmehta13** [comment]
Ref: https://github.com/Baseflow/flutter-geolocator/pull/1202
