### ISSUE TITLE
flutter-background-location-tracker service not working when screen is OFF for long run

### ISSUE THREAD

**Issue by Sharath-B-Naik** [icapps/flutter-background-location-tracker#44]
Hi, I'm using this plugin for track user's location in  background. This works perfectly when screen is ON even app killed (removed from recent apps). But this stops working after couple of minutes when screen is OFF. 
i noticed after 10 minutes this stops working.

can you help me to solve this issue ?

**Comment by ikbendewilliam** [comment]
Hi, what OS are you experiencing this on?
On Android there is a battery saving system that shuts apps down in the background to increase the battery life. 
You can disable this behavior for your app by asking for the battery saving permission. See this [plugin](https://pub.dev/packages/disable_battery_optimization) for more info.

Is there a notification shown that the app is running in the background?

**Comment by Sharath-B-Naik** [comment]
Thank you. Issue solved by disabling battery optimisation.

**Comment by Sharath-B-Naik** [comment]
Thank you. Issue solved by disabling battery optimisation.

**Comment by harivyas07** [comment]
Hi for me unfortunately this solution is not working , OS android 12 , phone Samsung S10 , the background tracking works perfectly when the phone screen is not off and when I lock the screen the app works in background for only 2 mins and then I don’t receive any location updates . I tried to make the battery optimisation as unrestricted but still no luck

**Comment by ikbendewilliam** [comment]
@harivyas07 did you ask for the always permission? On Android you have to first ask for location permission and then the location always permission.

**Comment by harivyas07** [comment]
Yes I did asked always permission but still no luck

**Comment by harivyas07** [comment]
@ikbendewilliam Anything you can help me with as the background functionality is not working when the phone screen is off ( stops working after   2 mins )

**Comment by ikbendewilliam** [comment]
@harivyas07 I don't immediately know. If you have permissions for battery saver and location always it should work fine in the background. Some things you can try: 
- Run the example project, does this work in the background? 
- Run on a different device?
- Do you encounter an error?
