### ISSUE TITLE
No location updates after first one

### ISSUE THREAD

**Issue by oussamaniba** [icapps/flutter-background-location-tracker#46]
I'm only able to get the first location from the listener in ANDROID only

`I/flutter (19669): locationUpdate: {lat: 32.2333, lon: -5.53321, alt: 0.0, vertical_accuracy: 0.5, horizontal_accuracy: 5.0, course: 36.11000061035156, course_accuracy: 30.0, speed: 23.113969802856445, speed_accuracy: 0.5, logging_enabled: true}
I/flutter (19669): Location Update: Lat: 35.84597 Lon: -5.54432
D/BackgroundManager(19669): Got success, destroy engine!`

And after the Got success, no location is received

I tried it on your example code without changing anything and same result I tried updating Google Play service location to version 21 and still the same thing

**Comment by oussamaniba** [comment]
UPDATE:

On an emulator running SDK 33 I've got this and I think it comes from Geolocator dependency. It's some sort of conflict between both packages

I/flutter (13881): locationUpdate: {lat: 35.8527348, lon: -5.5378524, alt: 0.0, vertical_accuracy: 0.5, horizontal_accuracy: 5.0, course: 38.32645034790039, course_accuracy: 30.0, speed: 21.961938858032227, speed_accuracy: 0.5, logging_enabled: true}
D/BackgroundManager(13881): Got success, destroy engine!
D/FlutterGeolocator(13881): Disposing Geolocator services
E/FlutterGeolocator(13881): Geolocator position updates stopped
D/FlutterGeolocator(13881): Stopping location service.

**Comment by dJani97** [comment]
There is another issue related to the geolocator package, maybe they are related? 

https://github.com/icapps/flutter-background-location-tracker/issues/43

**Comment by oussamaniba** [comment]
Unfortunately, no the app isn't crashing due to a conflict of the google play service, it's working but when running alongside Geolocator it seems that one is trying to over-run the other

**Comment by gauravmehta13** [comment]
@oussamaniba  Can you please check https://github.com/icapps/flutter-background-location-tracker/issues/43 as well, It would be great if this package can support latest  play-services:location version

**Comment by agutf** [comment]
I'm having the same issue. In Android no location updates after the first one... In iOS everything works.

Is there any workaround to solve this?

**Comment by oussamaniba** [comment]
https://github.com/Yukams/background_locator_fixed/issues/64#issuecomment-1459845605

I have put a solution here and I forgot to add here maybe or my comment was deleted idk 

Anyway this is a working solution for me and I think for you too

**Comment by ikbendewilliam** [comment]
@oussamaniba Are you still having these issues? There was indeed an issue with the play services, that has been fixed

**Comment by oussamaniba** [comment]
Yeah it was solved, using two packages one for each platform, but thanks anyways!
