### ISSUE TITLE
Missing Plugins Error

### ISSUE THREAD

**Issue by JonathanWilbur** [icapps/flutter-background-location-tracker#61]
Hello. I know you have a description of what to do about some missing plugins error on the README, but it seems like it is cut off or incomplete or something. I am having that exact error when running code very similar to the example code:

```
MissingPluginException (MissingPluginException(No implementation found for method initialize on channel com.icapps.background_location_tracker/foreground_channel))
```

This happens on the `  await BackgroundLocationTrackerManager.initialize(` line.

I have checked that my Gradle configuration are set to 30 as your documentation requires.

**Comment by vanlooverenkoen** [comment]
Can you provide us with a git repo to have a reproducable test case? 
Do you have the same issue with the example project?

**Comment by JonathanWilbur** [comment]
I will try with the example project (good idea). In the meantime, here is my repo, in case anything stands out to you: https://github.com/JonathanWilbur/fmx-beacon

**Comment by ikbendewilliam** [comment]
@JonathanWilbur Is this still the case?

**Comment by JonathanWilbur** [comment]
I have put this project on pause for now. I will close this issue to avoid polluting your issues list. Thank you for your help!
