### ISSUE TITLE
Hide Notification bar

### ISSUE THREAD

**Issue by priyanka2386** [icapps/flutter-background-location-tracker#73]
How can I hide notification bar when app goes in to background or kill the app.

**Comment by ikbendewilliam** [comment]
https://developer.android.com/develop/background-work/services/foreground-services
> Foreground services show a [status bar notification](https://developer.android.com/develop/ui/views/notifications), to make users aware that your app is performing a task in the foreground and is consuming system resources.

> Only use a foreground service when your app needs to perform a task that is noticeable by the user, even when they're not directly interacting with the app. If the action is of low enough importance that you want to use a minimum-priority notification, create a [background task](https://developer.android.com/topic/performance/scheduling#categories_of_background_tasks) instead.

So the system always shows a (minimum-priority) notification.
